API-Task/Models/Beer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APITask.Models
{
    public class Beer
    {
        public Int64 Id { get; set; }
        public String Name { get; set; }
        public String Image_url { get; set; }
        public String Description { get; set; }
        public String First_brewed { get; set; }
        public String ABV { get; set; }
        public List<String> Food_pairing { get; set; }
        public Volume Volume { get; set; }
    }

    public class Volume
    {
        public Double Value { get; set; }
        public String Unit { get; set; }
    }
}

API-Task/Models/ErrorViewModel.cs
using System;

namespace API_Task.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

API-Task/Controllers/BeerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using APITask.Models;
using Microsoft.AspNetCore.Mvc;

namespace APITask.Controllers
{
    public class BeerController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Index()
        {
            IEnumerable<Beer> beers = null;

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.punkapi.com/v2/");
                //String query = Request.QueryString.ToString();

                String getString = "beers";

                var query = Request.Query;

                if (query.Count != 0)
                {
                    var queryList = new List<KeyValuePair<String, Microsoft.Extensions.Primitives.StringValues>>();

                    foreach (var q in query)
                    {
                        if (!String.IsNullOrEmpty(q.Value.ToString()))
                            queryList.Add(q);
                    }

                    if (queryList.Count != 0)
                    {
                        getString = String.Concat(getString, "?");

                        foreach (var q in queryList)
                        {
                            getString = String.Concat(getString, q.Key, "=", q.Value.ToString(), "&");
                        }

                        getString.Remove(getString.Length - 1);
                    }


                }
                //String getString = String.Concat("beers", query);

                Task<HttpResponseMessage> responseTask = client.GetAsync(getString);
                responseTask.Wait();

                HttpResponseMessage result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    Task<IList<Beer>> readTask = result.Content.ReadAsAsync<IList<Beer>>();
                    readTask.Wait();
                    beers = readTask.Result;
                }
                else
                {
                    beers = Enumerable.Empty<Beer>();

                    ModelState.AddModelError(String.Empty, "Server error");
                }
            }
            return View(beers);
        }

        public IActionResult Random()
        {
            Beer beer = null;

            Random random = new Random();
            Int32 randomNum = random.Next(1, 326);

            using (HttpClient client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://api.punkapi.com/v2/");

                Task<HttpResponseMessage> responseTask = client.GetAsync(String.Concat("beers/", randomNum.ToString()));
                responseTask.Wait();

                HttpResponseMessage result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    Task<IList<Beer>> readTask = result.Content.ReadAsAsync<IList<Beer>>();
                    readTask.Wait();
                    beer = readTask.Result.FirstOrDefault();
                }
                else
                {
                    beer = null;

                    ModelState.AddModelError(String.Empty, "Server error");
                }
            }

            return View(beer);
        }

    }
}

API-Task/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using API_Task.Models;

namespace API_Task.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

API-Task/Views/Beer/Index.cshtml
@model IEnumerable<APITask.Models.Beer>

@{
    ViewData["Title"] = "Beers";
}

<h2>Beers</h2>

<form method="get" asp-action="Index">
    <label for="name">Beer name</label>
    <input type="text" name="beer_name" placeholder="Beer name"/>
    <label for="date">Brewed before</label>
    <input type="text" name="brewed_before" placeholder="MM/yyyy"/>
    <input type="submit" value="Search" />
</form>

<br />

<form method="get" asp-action="Random">
    <input type="submit" value="Random Beer" />
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.Image_url) *@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.First_brewed)*@
                First brewed
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ABV)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Food_pairing)*@
                Food pairings
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img height="300" src="@Html.DisplayFor(modelItem => item.Image_url)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.First_brewed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ABV)
                </td>
                <td>
                    <table>
                        @foreach (var i in item.Food_pairing)
                        {
                            <tr style="border-bottom: 1px solid black;">
                                <td> @i </td>
                            </tr>
                        }
                    </table>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume.Value) @Html.DisplayFor(modelItem => item.Volume.Unit)
                </td>
            </tr>
        }
    </tbody>
</table>

API-Task/Views/Beer/Random.cshtml
@model APITask.Models.Beer

@{
    ViewData["Title"] = "Beers";
}

<h2>Beers</h2>

<form method="get" asp-action="Index">
    <label for="name">Beer name</label>
    <input type="text" name="beer_name" placeholder="Beer name"/>
    <label for="date">Brewed before</label>
    <input type="text" name="brewed_before" placeholder="MM/yyyy"/>
    <input type="submit" value="Search" />
</form>

<br />

<form method="get" asp-action="Random">
    <input type="submit" value="Random Beer" />
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.Image_url) *@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.First_brewed)*@
                First brewed
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ABV)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Food_pairing)*@
                Food pairings
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Volume)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td>
                <img height="300" src="@Html.DisplayFor(modelItem => Model.Image_url)" alt="No picture available" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.First_brewed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.ABV)
            </td>
            <td>
                <table >
                    @foreach (var i in Model.Food_pairing)
                    {
                        <tr style="border-bottom: 1px solid black;">
                            <td> @i </td>
                        </tr>
                    }
                </table>
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Volume.Value) @Html.DisplayFor(modelItem => Model.Volume.Unit)
            </td>
        </tr>
    </tbody>
</table>

API-Task/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

API-Task/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

API-Task/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

API-Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - API_Task</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">API_Task</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Beer" asp-action="Index">Beers</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - API_Task</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>